const trendingProductsData = [
  {
    id: 1,
    title: "iPhone 16 Pro",
    image: "/products/iphone.png",
    price: 119999,
    oldPrice: 129999,
    discount: 8,
    rating: 4.9,
  },
  {
    id: 2,
    title: "Sony WH-1000XM5",
    image: "/products/headphone.png",
    price: 24999,
    oldPrice: 29999,
    discount: 17,
    rating: 4.9,
  },
  {
    id: 3,
    title: "Gaming Laptop",
    image: "/products/laptop.png",
    price: 84999,
    oldPrice: 99999,
    discount: 15,
    rating: 4.8,
  },
  {
    id: 4,
    title: "Apple Watch",
    image: "/products/watch.png",
    price: 35999,
    oldPrice: 42999,
    discount: 16,
    rating: 4.8,
  },
  {
    id: 5,
    title: "Nike Air Max",
    image: "/products/shoe.png",
    price: 4999,
    oldPrice: 7999,
    discount: 38,
    rating: 4.8,
  },
  {
    id: 6,
    title: "Bluetooth Speaker",
    image: "/products/speaker.png",
    price: 2999,
    oldPrice: 4999,
    discount: 40,
    rating: 4.7,
  },
];

export default trendingProductsData;